app_productos/urls.py
from django.contrib import admin
from django.urls import path , include




from .views import      ProductoListView   
            

app_name = "productos"

urlpatterns = [
    path("", ProductoListView.as_view(), name="all")
    
]

pet_Shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import IndexPage , Contacto, Tienda


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexPage.as_view(), name = "index"),
    path("contacto/", Contacto.as_view(), name="contacto"),

    path("tienda/" , Tienda.as_view(), name= "tienda"),
    path('productos/', include('app_productos.urls'))

]

from django.conf import settings
from django.conf.urls.static import static
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_productos/models.py
from django.db import models
from django.db.models import Model

class Producto(Model):
     
    tipo_choices = [
        ("seco", "Productos Secos"),
        ("humedo", "Productos Humedos"),
        ("juego", "Jueguetes")
        
    ]
    
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo = models.CharField(max_length=10, choices=tipo_choices)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)


    def __str__(self):
        return self.nombre

    class Meta:
         db_table = "productos_table"

app_productos/views.py
# app_productos/views.py

from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
''' from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView '''


from .models import Producto


class ProductoBaseView(View):
    template_name = 'productos.html'
    model = Producto
    fields = '__all__'
    success_url = reverse_lazy('producto:all')


class ProductoListView(ProductoBaseView,ListView):
    ...
 
# 
# class ProductoDetailView(ProductoBaseView,DetailView):
#     template_name = "vino_detail.html"

# class ProductoCreateView(ProductoBaseView,CreateView):
#     template_name = "vino_create.html"
#     extra_context = {
#         "tipo": "Crear"
#     }


# class ProductoUpdateView(ProductoBaseView,UpdateView):
#     template_name = "vino_create.html"
#     extra_context = {
#         "tipo": "Actualizar "
#     }

# class ProductoDeleteView(ProductoBaseView,DeleteView):
#     template_name = "vino_delete.html"
#     extra_context = {
#         "tipo": "Borrar "
#     }
#  
    
    
    
    
''' 
from django.shortcuts import render
from .models import Producto

def home(request):
    return render(request, 'index.html') '''

pet_Shop/views.py
from django.views.generic import TemplateView

class IndexPage (TemplateView):
    template_name = "index.html"

class Contacto (TemplateView):
    template_name = "contacto.html"    


class Tienda (TemplateView):
    template_name = "tienda.html"   


# views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render

@staff_member_required
def vista_que_requiere_login(request):
    # Tu lógica de vista aquí
    return render(request, 'adim:index')

app_productos/templates/productos.html
{%load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static './css/mascota.css' %}" rel="stylesheet">
    <link href="{% static './css/style.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <title>PRODUCTOS </title>
</head>
<body>
    <header>

        <h2>Productos para Perros </h2>
         <div id="header"> <a href="#" id="logo"><img src="{% static './media/logo.png' %}" width="250" height="auto" alt=""></a>
   
         <select class="form-select" aria-label="Default select example">
           <option selected>Open this select menu</option>
           <option value="Pruductos Secos">One</option>
           <option value="Productos humedos ">Two</option>
           <option value="Juguetes">Three</option>
        </select>
   
   </header>
   
   
   <main>
       <div id= "miTitulo">  <!-- Modifica tu sección en el archivo HTML para mostrar los productos -->
       <section>
           {% for producto in producto_list %}
           <div class="producto">
           <img src={{ producto.imagen.url }}>
               <h2>{{ producto.nombre }}</h2>
               <p>{{ producto.descripcion }}</p>
               <p>Precio: ${{ producto.precio }}</p>
               <button>detalle</button>
   
           </div>
   
          </div>
           {% endfor %}
       </section>
       </div>
   
           <a href="{% url 'productos:all' %}">Volvamos al Inicio</a>
       </div>
   </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>
</body>
</html>

templates/contacto.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
  <title>Pet Shop</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{%static './css/style.css' %}" rel="stylesheet" />

</head>


<body>
  <header>

    <div id="body">
      <div id="header"> <a href="#" id="logo"><img src="{% static './media/logo.png' %}" width="250" height="auto" alt=""></a>
        <ul class="navigation">
          <li class="active"><a href="{% url 'index' %}">Nosotros</a></li>
          <li><a href="{% url 'tienda' %}">Tienda</a></li>
          <li><a href="{% url 'contacto' %}">Contactanos</a></li>
        </ul>
      </div>
  </header>

<main>

  <div class="contenedor-formulario">
    <form action="https://sheetdb.io/api/v1/nu5diyqjgddny" method="post" id="PedidosPetShop">

      <span><i class="fa fa-address-card" style="color: #006d8f;"></i></span>
      <h2>Información de contacto</h2>
      <br>

      <div>
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="data[Nombre]" />
      </div>
      <div>
        <label for="mail">Correo electrónico:</label>
        <input type="email" id="mail" name="data[Email]" />
      </div>
      <div>
        <label for="msg">Comentario:</label>
        <textarea id="msg" name="data[Comentario]"></textarea>
      </div>
      <div class="button">

        <button type="submit">
          <h2>Envia tu mensaje</h2>
        </button>
      </div>
    </form>
  </div>


  <div class="Ubicacion">
    <center>
      <h2>Ubicacion</h2>
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3287.092831195893!2d-58.55463392523134!3d-34.52587597298235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2sar!4v1696686201122!5m2!1ses!2sar"
        width="500" height="250" style="border: 1" allowfullscreen="" loading="lazy"
        referrerpolicy="no-referrer-when-downgrade">
      </iframe>
      <h3>Av. Iraola 243, B1900 La Plata, Provincia de Buenos Aires</h3>
    </center>
  </div><br><br>

</main>


<footer>

  <div id="footer">
    <center>
      <h2> María - Pablo - Liliana </h2>
    </center>
  </div>


</footer>

<script src="{% static './js/style.js' %}"></script>
<script src="{% static './js/form.js' %}"></script>

</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>Pet Shop</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{% static './css/style.css' %}" rel="stylesheet" />
  <link href="{% static './css/banner.css' %}" rel="stylesheet" />

</head>

<body>
  <header>
    <div id="body">
      <div id="header"> <a href="#" id="logo"><img src="{% static './media/logo.png' %}" width="250" height="auto" alt=""></a>
        <ul class="navigation">
          <li class="active"><a href="{% url 'index' %}">Nosotros</a></li>
          <li><a href="{% url 'tienda' %}">Tienda</a></li>
          <li><a href="{% url 'contacto' %}">Contactanos</a></li>
        </ul>
      </div>
  </header>

  <main>

    <div id="content">
      <div class="imagen-responsive">&nbsp;</div>

      <div class="content">
        <ul>
          <li> <img src="{% static './media/Alimentacion.png' %}" width="114" height="160" alt="" class="imagen-con-zoom"></a>
            <h2>¿Los alimentos crudos pueden enfermar a las mascotas?</h2>
            <p>Los CDC no recomiendan darles alimentos crudos a las mascotas.
              Se han encontrado bacterias como Salmonella y Listeria en los alimentos crudos para mascotas, incluso en
              los
              envasados que se venden en las tiendas. Estos microbios pueden enfermar a su mascota. Su familia también
              se
              puede enfermar al manipular el alimento crudo o cuidar a la mascota.</p>
          </li>
          <li> <img src="{% static './media/puppy2.jpg' %}" width="114" height="160" alt="" class="imagen-con-zoom"></a>
            <h2>¿Alimentos secos o enlatados para mascotas?</h2>
            <p>Los alimentos secos o enlatados también pueden estar contaminados con microbios. Antes de hacer cambios
              en
              la alimentación de su mascota, hable con su veterinario.</p>
          </li>
          <li> <img src="{% static './media/cat.jpg' %}" width="114" height="160" alt="" class="imagen-con-zoom"></a>
            <h2>La mascota adecuada para tu familia</h2>
            <p>Algunas mascotas tienen buen carácter y son más adecuadas para estar con niños: Los perros tales como los
              labradores, los golden retriever (perdiguero dorado) y los beagle (sabueso) tienden a ser cariñosos con
              los
              niños.</p>
          </li>
        </ul>
      </div>

     
    <div id="main">
      <center>
        <h1>¡Lo llevamos a tu casa!</h1>
      </center>
      <div class="banner">
        <img src="{% static './media/002.png' %}" alt="">
        <img src="{% static './media/007.png' %}" alt="">
        <img src="{% static './media/008.png' %}" alt="">
        <img src="{% static './media/images (5).jpeg' %}" alt="">
        <img src="{% static './media/images (1).jpeg' %}" alt="">
        <img src="{% static './media/descarga (1).jpeg' %}" alt="">
      </div>
    </div>

    <section>
      
      <h1>Estos son algunos de nuestros amigos !!!</h1>
      <div id="imagenesMascotas"></div>
      <button id="botonNuevasImagenes">Obtener Nuevas Imágenes</button>

    </section>
    
  </main>

  <footer>
    <div id="footer">
      <center>
        <h2> María - Pablo - Liliana </h2>
      </center>
    </div>

  </footer>

  <script type="module" src="{%static './js/style.js' %}"></script>
 

</body>

</html>

templates/tienda.html
{% load static %}

<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{% static './css/mascota.css' %}" rel="stylesheet">
  <link href="{% static './css/style.css' %}" rel="stylesheet" />

  <title>Pet Shop</title>

</head>

<body>

  <header>
    <div id="header"> <a href="#" id="logo"><img src="{% static './media/logo.png' %}" width="250" height="auto" alt=""></a>
      <ul class="navigation">
        <li class="active"><a href="{%url 'index' %}">Nosotros</a></li>
        <li><a href="{% url 'tienda' %}">Tienda</a></li> 
        <li><a href="{% url 'contacto' %}">Contactanos</a></li>

        {% if user.is_authenticated %}
           <li><a href="{% url 'admin:index' %}"><button>Panel de Administración</button></a></li>
        {% else %}
           <li><a href="{% url 'admin:login' %}"><button>Iniciar sesión en el Panel de Administración</button></a></li>
        {% endif %}
        
      </ul>
    </div>
  </header>

  <main>
    <center>
      <h2>Productos</h2>
      <div class="container">
        <picture>
          <button>
            <h2>Perros</h2>
            <a href="{% url 'productos:all' %}">
              <img
                src="https://media.istockphoto.com/id/1344938288/es/foto/hombre-feliz-entrenando-con-su-perro-en-la-naturaleza.jpg?s=612x612&w=0&k=20&c=PxgKJuA9CyS_468SwZ5LkjL_eT04-ULG3FoaXRuws1s="
                alt="PERROS"></a>
        </picture></button>


        <picture> <button>
            <h2>Gatos</h2>
            <a href="{% url 'productos:all' %}" target="_blank">
              <img
                src="https://media.istockphoto.com/id/1185437742/es/foto/vista-de-cerca-de-tabby-gatito-lindo-mascotas-y-concepto-de-estilo-de-vida-precioso-gato.jpg?s=612x612&w=0&k=20&c=5F985M2KmRXvvjbSP5GovzcYpi4M66ZkJu4J7hmOmEM="
                alt="GATOS" /></a></picture></button>
      </div>
    </center>
  </main>

  <footer>
    <div id="footer">
      <center>
        <h2> Mary - Pablo - Liliana </h2>
      </center>

  </footer>

</body>

</html>